site_name: Emerge

theme:
  name: "material"
  features:
    - search.suggest
    - sarch.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    # Palette toggle for light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - mkdocstrings
  - search 

repo_url: https://github.com/nrel/emerge
repo_name: nrel/emerge



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.33.1/plotly.min.js


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite
  - pymdownx.details


nav:
  - Welcome: index.md
  - Tutorials: 
    - Getting started: getting_started.md
  - How to Guides: how-to-guides.md
  - References: reference.md
  - Guide to Developers: developers-guide.md