master: ../../examples/opendss/master.dss
start_time: "2018-01-01 06:00:00"
end_time: "2018-01-01 13:00:00"
profile_start: "2018-01-01 00:00:00"
export_path: './metrics'
resolution_min: 60
multi_scenario: 
  scenario_folder: ./scenarios
  num_core: 2
  pv_profile_shape: 'pvshape'
metrics:
  node_voltage_stats:
    export_type: 'csv'
    file_name: 'node_voltage_stats.csv'
  node_voltage_bins:
    export_type: 'csv'
    file_name: 'node_voltage_bins.csv'
    voltage_bins: [0.95, 0.98, 1.02, 1.05]
  substation_power:
    export_type: 'csv'
    file_name: 'substation_power_timeseries.csv'
  total_powerloss:
    export_path: 'csv'
    file_name: 'total_loss.csv'
  line_loading_stats:
    export_type: 'csv'
    file_name: 'line_loading_stats.csv'
  line_loading_bins:
    export_type: 'csv'
    file_name: 'line_loading_bins.csv'
    loading_bins: [0.5, 1.0, 1.2]
  xfmr_loading_stats:
    export_type: 'csv'
    file_name: 'xfmr_loading_stats.csv'
  xfmr_loading_bins:
    export_type: 'csv'
    file_name: 'xfmr_loading_bins.csv'
    loading_bins: [0.5, 1.0, 1.2]



